rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('category/<slug:category_name_slug>/', views.ShowCategoryView.as_view(), name='show_category'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.AddPageView.as_view(), name='add_page'),
    # path('register/', views.register, name='register'),
    # path('login/', views.user_login, name='login'),
    path('restricted/', views.RestrictedView.as_view(), name='restricted'),
    # path('logout/', views.user_logout, name='logout'),
    # path('search/', views.search, name='search'),
    path('goto/', views.GotoView.as_view(), name='goto'),
    path('register_profile/', views.RegisterProfileView.as_view(), name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
    path('like_category/', views.LikeCategoryView.as_view(), name='like_category'),
    path('suggest/', views.CategorySuggestionView.as_view(), name='suggest'),
    path('search_add_page/', views.SearchAddPageView.as_view(), name='search_add_page'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from rango import views
from registration.backends.simple.views import RegistrationView
from django.urls import reverse

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/register/', MyRegistrationView.as_view(), name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils import timezone

class Category(models.Model):
    NAME_MAX_LENGTH = 128
    
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        # Testing chapter -- added test to ensure that views is non-negative.
        if self.views < 0:
            self.views = 0
        
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name

class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200
    
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)
    last_visit = models.DateTimeField(blank=True)
    
    def save(self, *args, **kwargs):
        self.last_visit = timezone.now()
        super(Page, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    
    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)
    
    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=Page.URL_MAX_LENGTH, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url
            
            return cleaned_data
    
    class Meta:
        model = Page
        exclude = ('category',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rango.bing_search import run_query
from django.views import View
from django.utils.decorators import method_decorator
from rango.models import UserProfile
from django.contrib.auth.models import User
from django.utils import timezone

class IndexView(View):
    def get(self, request):
        category_list = Category.objects.order_by('-likes')[:5]
        page_list = Page.objects.order_by('-views')[:5]
    
        context_dict = {}
        context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
        context_dict['categories'] = category_list
        context_dict['pages'] = page_list
    
        visitor_cookie_handler(request)
    
        response = render(request, 'rango/index.html', context_dict)
    
        return response

class AboutView(View):
    def get(self, request):
        context_dict = {}
        context_dict['visits'] = request.session['visits']
        
        return render(request, 'rango/about.html', context_dict)

class ShowCategoryView(View):
    def create_context_dict(self, category_name_slug):
        """
        A helper method that was created to demonstrate the power of class-based views.
        You can reuse this method in the get() and post() methods!
        """
        context_dict = {}
        
        try:
            category = Category.objects.get(slug=category_name_slug)
            pages = Page.objects.filter(category=category).order_by('-views')
        
            context_dict['pages'] = pages
            context_dict['category'] = category
        except Category.DoesNotExist:
            context_dict['category'] = None
            context_dict['pages'] = None
        
        return context_dict
    
    def get(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        return render(request, 'rango/category.html', context_dict)
    
    def post(self, request, category_name_slug):
        context_dict = self.create_context_dict(category_name_slug)
        query = request.POST['query'].strip()
        
        if query:
            context_dict['result_list'] = run_query(query)
            context_dict['query'] = query
        
        return render(request, 'rango/category.html', context_dict)

class AddCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = CategoryForm()
        return render(request, 'rango/add_category.html', {'form': form})
    
    @method_decorator(login_required)
    def post(self, request):
        form = CategoryForm(request.POST)
        
        if form.is_valid():
            form.save(commit=True)
            return index(request)
        else:
            print(form.errors)
        
        return render(request, 'rango/add_category.html', {'form': form})

class AddPageView(View):
    def get_category_name(self, category_name_slug):
        """
        A helper method that was created to demonstrate the power of class-based views.
        You can reuse this method in the get() and post() methods!
        """
        try:
            category = Category.objects.get(slug=category_name_slug)
        except Category.DoesNotExist:
            category = None
        
        return category
    
    @method_decorator(login_required)
    def get(self, request, category_name_slug):
        form = PageForm()
        category = self.get_category_name(category_name_slug)
        context_dict = {'form': form, 'category': category}
        return render(request, 'rango/add_page.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, category_name_slug):
        form = PageForm(request.POST)
        category = self.get_category_name(category_name_slug)
        
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                
                return HttpResponseRedirect(reverse('rango:show_category', kwargs={'category_name_slug':category_name_slug}))
        else:
            print(form.errors)
        
        context_dict = {'form': form, 'category': category}
        return render(request, 'rango/add_page.html', context_dict)

class RestrictedView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'rango/restricted.html')

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    
    if not val:
        val = default_val
    
    return val

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')
    
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie
    
    request.session['visits'] = visits

class GotoView(View):
    def get(self, request):
        page_id = request.GET.get('page_id')
        
        try:
            selected_page = Page.objects.get(id=page_id)
        except Page.DoesNotExist:
            return redirect(reverse('rango:index'))
            
        selected_page.views = selected_page.views + 1
        selected_page.last_visit = timezone.now()
        selected_page.save()
        
        return redirect(selected_page.url)

class RegisterProfileView(View):
    @method_decorator(login_required)
    def get(self, request):
        form = UserProfileForm()
        context_dict = {'form': form}
        return render(request, 'rango/profile_registration.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request):
        form = UserProfileForm(request.POST, request.FILES)
        
        if form.is_valid():
            user_profile = form.save(commit=False)
            user_profile.user = request.user
            user_profile.save()
            
            return redirect('rango:index')
        else:
            print(form.errors)
        
        context_dict = {'form': form}
        return render(request, 'rango/profile_registration.html', context_dict)

class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        
        userprofile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': userprofile.website,
                                'picture': userprofile.picture})
        
        return (user, userprofile, form)
    
    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, userprofile, form) = self.get_user_details(username)
        except TypeError:
            return redirect('rango:index')
        
        context_dict = {'userprofile': userprofile,
                        'selecteduser': user,
                        'form': form}
        
        return render(request, 'rango/profile.html', context_dict)
    
    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, userprofile, form) = self.get_user_details(username)
        except TypeError:
            return redirect('rango:index')
        
        if user == request.user:  # Added for authentication exercise.
            form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        
            if form.is_valid():
                form.save(commit=True)
                return redirect('rango:profile', user.username)
            else:
                print(form.errors)
        
            context_dict = {'userprofile': userprofile,
                            'selecteduser': user,
                            'form': form}
        
        return render(request, 'rango/profile.html', context_dict)

class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()
        
        return render(request,
                      'rango/list_profiles.html',
                      {'userprofile_list': profiles})

class LikeCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        category_id = request.GET['category_id']
        
        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)
        
        category.likes = category.likes + 1
        category.save()
        
        return HttpResponse(category.likes)

def get_category_list(max_results=0, starts_with=''):
    category_list = []
    
    if starts_with:
        category_list = Category.objects.filter(name__istartswith=starts_with)
    
    if max_results > 0:
        if len(category_list) > max_results:
            category_list = category_list[:max_results]
    
    return category_list

class CategorySuggestionView(View):
    def get(self, request):
        suggestion = request.GET['suggestion']
        category_list = get_category_list(max_results=8, starts_with=suggestion)
        
        if len(category_list) == 0:
            category_list = Category.objects.order_by('-likes')
        

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About Rango
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumotron-heading">Rango About Page</h1>
        </div>
    </div>
    
    <div>
        Here is the about page.<br />
        <strong>This tutorial has been put together by wensden.</strong><br />
        
        <p>Visits: {{ visits}}</p>
        
        <img src="{% static 'images/rango.jpg' %}" alt="Picture of Rango" />
        <!-- <img src="{{ MEDIA_URL}}cat.jpg" alt="Picture of a Cat" /> -->
    </div>
    
    <button class="btn btn-primary" onclick="alert('You clicked the button using inline JavaScript.');">
        Click me - I run on vanilla JavaScript!
    </button>
    
    <button class="btn btn-primary" id="about-btn">
        Click me - I'm using JQuery!
    </button>
    
    <p>This is some text for the JQuery example.</p>
    
    <div id="msg">Hello! I'm a further example for JQuery testing.</div>
    
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumotron-heading">Add a Category</h1>
        </div>
    </div>
        
    <div class="container">
        <div class="row">
            <form role="form" id="category_form" method="post" actions="{% url 'rango:add_category' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}<br />
                    {{ field }}<br />
                    <div class="p-2"></div>
                {% endfor %}
                <button class="btn btn-primary" type="submit" name="submit">
                    Add Category
                </button>
                <div class="p-5"></div>
            </form>
        </div>
    </div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
        {% if category %}
        <div class="jumbotron p-4">
            <div class="container">
                <h1 class="jumotron-heading">Add Page to {{ category.name }}</h1>
            </div>
        </div>
        
        <div class="container">
            <div class="row">
                <form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}">
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}
                    {% for field in form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }}<br />
                        {{ field }}<br />
                        <div class="p-2"></div>
                    {% endfor %}
                    <br />
                    <button class="btn btn-primary" type="submit" name="submit">
                        Add Page
                    </button>
                    <div class="p-5"></div>
                </form>
            </div>
        </div>
        {% else %}
        <div class="jumbotron p-4">
            <div class="container">
                <h1 class="jumotron-heading">Add a Page</h1>
            </div>
        </div>
        
        <div>
            The specified category does not exist.
        </div>
        {% endif %}
{% endblock %}

templates/rango/base-old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Rango - 
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <div>
            {% block body_block %}
            {% endblock %}
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock %}
        </div>
        <hr />
        <div>
            <ul>
            {% if user.is_authenticated %}
                <!-- Show these links when the user is logged in -->
                <li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_password_change' %}">Change your Password</a></li>
                <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
            {% else %}
                <!-- Show these links when the user is NOT logged in -->
                <li><a href="{% url 'auth_login' %}">Login</a></li>
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
            {% endif %}
                <!-- Outside the conditional statements, ALWAYS show -->
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">
    </head>
    
    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid">
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="ml-3 w-75">
                        <input type="search" id="search-input" class="form-control ds-input" placeholder="Search..." />
                    </div>
                    <div class="sidebar-sticky" id="categories-listing">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2019 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="{% static "js/jquery-3.3.1.min.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "js/rango-jquery.js" %}" crossorigin="anonymous"></script>
        <script src="{% static "js/rango-ajax.js" %}" crossorigin="anonymous"></script>
        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
    </body>
</html>

templates/rango/categories.html
<ul class="nav flex-column">
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
            <li class="nav-item"><a class="nav-link active" href="{% url 'rango:show_category' c.slug %}"><span data-feather="archive"></span>{{ c.name }}</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'rango:show_category' c.slug %}"><span data-feather="archive"></span>{{ c.name }}</a></li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li class="nav-item">There are no categories present.</li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
    {{ category.name }}
    {% else %}
    Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
        <div class="jumbotron p-4">
            <div class="container">
                <h1 class="jumotron-heading">{{ category.name }}</h1>
                
                <div>
                    <strong id="like_count">{{ category.likes }}</strong> likes
                    {% if user.is_authenticated %}
                    <button id="like_btn" data-categoryid="{{ category.id }}" class="btn btn-primary btn-sm" type="button">
                        <span data-feather="thumbs-up"></span>
                        Like Category
                    </button>
                    {% endif %}
                </div>
                
            </div>
        </div>
        
        <!-- Added page-listing div for adding a page AJAX functionality. -->
        <div id="page-listing">
        {% if pages %}
        <ul>
            {% for page in pages %}
            <li>
                <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
                {% if page.views > 1 %}
                    ({{ page.views }} views)
                {% elif page.views == 1 %}
                    ({{ page.views }} view)
                {% endif %}
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <strong>No pages currently in category.</strong>
        {% endif %}
        </div>
        
        {% if user.is_authenticated %}
        <a href="{% url 'rango:add_page' category.slug %}">Add Page</a>
        {% endif %}
        
        {% if user.is_authenticated %}
        <div>
            <form class="form-inline" id="user-form" method="post" action="{% url 'rango:show_category' category.slug %}">
                {% csrf_token %}
            
                <div class="form-group">
                    <input class="form-control" type="text" size="50" name="query" value="{{ query }}" id="query" />
                </div>
            
                <button class="btn btn-primary" type="submit" name="submit">Search</button>
            </form>
        </div>
        
        <div>
            {% if result_list %}
                <h2>Results</h2>
            
                <div class="list-group">
                    {% for result in result_list %}
                        <div class="list-group-item">
                            <h3 class="list-group-item-heading">
                                <a href="{{ result.link }}">{{ result.title|safe|escape }}</a>
                                
                                <!-- Adding a button to add a page from search results -->
                                <button class="btn btn-info btn-sm rango-page-add"
                                        type="button"
                                        data-categoryid="{{ category.id }}"
                                        data-title="{{ result.title }}"
                                        data-url="{{ result.link }}">
                                    Add
                                </button>
                                <!-- End button -->
                            </h3>
                            <p class="list-group-item-text">{{ result.summary|safe|escape }}</p>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
        {% endif %}
        
    {% else %}
        The specified category does not exist!
    {% endif %}
{% endblock %}

templates/rango/page_listing.html
<!-- Taken directly from category.html for adding a page AJAX functionality. -->
{% if pages %}
<ul>
    {% for page in pages %}
    <li>
        <a href="{% url 'rango:goto' %}?page_id={{ page.id }}">{{ page.title }}</a>
        {% if page.views > 1 %}
            ({{ page.views }} views)
        {% elif page.views == 1 %}
            ({{ page.views }} view)
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% else %}
<strong>No pages currently in category.</strong>
{% endif %}

templates/rango/profile_registration.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register - Step 2
{% endblock %}

{% block body_block %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumotron-heading">Register for Rango - Step 2</h1>
        </div>
    </div>
    
    <div class="container">
        <div class="row">
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Create Profile" />
            </form>
        </div>
    </div>
{% endblock %}